# ==============================================================================
# ENGINE_ALPHA - ENTERPRISE TABULAR ENSEMBLE ENGINE
# Core Component: src/training/train_tabular.py
# Description: Evaluates XGBoost, LightGBM, and CatBoost using advanced Purged 
# Time-Series Cross-Validation. Dynamically auto-detects features generated by 
# the InstitutionalFeatureFactory, builds Out-Of-Fold (OOF) Level-1 Stacking 
# Matrices, and calculates deep probabilistic calibration metrics.
# ==============================================================================

import os
import sys
import yaml
import logging
import json
import numpy as np
import pandas as pd
import joblib
import time
import warnings
from typing import Tuple, List, Dict, Generator

# Machine Learning Libraries
import xgboost as xgb
import lightgbm as lgb
try:
    import catboost as cb
    CATBOOST_AVAILABLE = True
except ImportError:
    CATBOOST_AVAILABLE = False

from sklearn.metrics import (
    log_loss, 
    roc_auc_score, 
    accuracy_score, 
    brier_score_loss,
    precision_score,
    recall_score,
    f1_score
)

# Setup module-level logging
logging.basicConfig(
    level=logging.INFO,
    format="%(asctime)s [%(levelname)s] [TabularEngine] %(message)s",
    datefmt="%Y-%m-%d %H:%M:%S"
)
logger = logging.getLogger(__name__)
warnings.filterwarnings('ignore')

PROJECT_ROOT = os.path.abspath(os.path.join(os.path.dirname(__file__), "..", ".."))
if PROJECT_ROOT not in sys.path:
    sys.path.append(PROJECT_ROOT)

# ==============================================================================
# 1. PURGED TIME-SERIES CROSS VALIDATION
# ==============================================================================

class PurgedTimeSeriesSplit:
    """
    Marcos Lopez de Prado's Purged Time-Series Cross Validation.
    In financial/sequence data, training and testing sets cannot overlap temporally.
    If sequence_length is 60, there must be a 60-row "embargo" (purge window) 
    between the end of the train set and the beginning of the validation set to 
    prevent the XGBoost model from cheating via rolling averages.
    """
    def __init__(self, n_splits: int = 5, purge_window: int = 60, test_size_pct: float = 0.15):
        """
        Args:
            n_splits: Number of Walk-Forward folds.
            purge_window: The embargo size (must equal the max rolling window / seq_len).
            test_size_pct: What percentage of the data constitutes a validation fold.
        """
        self.n_splits = n_splits
        self.purge_window = purge_window
        self.test_size_pct = test_size_pct

    def split(self, X: np.ndarray) -> Generator[Tuple[np.ndarray, np.ndarray], None, None]:
        """Generates indices to split data into training and test set."""
        n_samples = len(X)
        test_size = int(n_samples * self.test_size_pct)
        train_step = int((n_samples - test_size) / self.n_splits)
        
        if train_step < self.purge_window:
            logger.warning("Train step is smaller than purge window! Reduce folds or increase data.")

        for i in range(self.n_splits):
            # Calculate dynamic bounds
            train_end = train_step * (i + 1)
            test_start = train_end + self.purge_window
            test_end = test_start + test_size
            
            # Boundary protections
            if test_start >= n_samples:
                break
            if test_end > n_samples:
                test_end = n_samples
                
            train_indices = np.arange(0, train_end)
            test_indices = np.arange(test_start, test_end)
            
            yield train_indices, test_indices

# ==============================================================================
# 2. PROBABILISTIC CALIBRATION & METRICS CALCULATOR
# ==============================================================================

class TabularMetricsEvaluator:
    """Computes high-fidelity institutional metrics for binary probabilistic classifiers."""
    
    @staticmethod
    def evaluate(y_true: np.ndarray, y_prob: np.ndarray, threshold: float = 0.5) -> Dict[str, float]:
        """Calculates a suite of performance metrics."""
        y_pred = (y_prob >= threshold).astype(int)
        
        # 1. Discrimination (Can it rank probabilities correctly?)
        try:
            auc = roc_auc_score(y_true, y_prob)
        except ValueError:
            auc = 0.5 # Failsafe if only one class is present
            
        # 2. Calibration (Are the probabilities mathematically truthful?)
        brier = brier_score_loss(y_true, y_prob)
        logloss = log_loss(y_true, y_prob)
        
        # 3. Hard Accuracy
        acc = accuracy_score(y_true, y_pred)
        prec = precision_score(y_true, y_pred, zero_division=0)
        rec = recall_score(y_true, y_pred, zero_division=0)
        f1 = f1_score(y_true, y_pred, zero_division=0)
        
        return {
            'AUC': float(auc),
            'Brier': float(brier),
            'LogLoss': float(logloss),
            'Accuracy': float(acc),
            'Precision': float(prec),
            'Recall': float(rec),
            'F1': float(f1)
        }

    @staticmethod
    def print_report(model_name: str, metrics: Dict[str, float]):
        """Standardized formatted console output."""
        logger.info(f"[{model_name} OOF] AUC: {metrics['AUC']:.4f} | Brier: {metrics['Brier']:.4f} | Acc: {metrics['Accuracy']:.2%}")

# ==============================================================================
# 3. THE MASTER TABULAR ENGINE
# ==============================================================================

class TabularEngine:
    """
    Trains and coordinates the Tabular Machine Learning cascade.
    Dynamically adapts to any arbitrary feature matrix.
    """
    def __init__(self, config_path: str = None):
        logger.info("="*70)
        logger.info("INITIATING INSTITUTIONAL TABULAR ENSEMBLE STACK")
        logger.info("="*70)
        
        if config_path is None:
            config_path = os.path.join(PROJECT_ROOT, "config", "global_config.yaml")
        
        with open(config_path, "r") as f:
            self.config = yaml.safe_load(f)
            
        # Directory Mapping
        self.data_path = os.path.join(PROJECT_ROOT, self.config['paths']['processed_data_path'])
        self.artifact_dir = os.path.join(PROJECT_ROOT, self.config['paths']['supervised_artifact_dir'])
        self.meta_dir = os.path.join(PROJECT_ROOT, self.config['paths']['meta_learner_artifact_dir'])
        
        os.makedirs(self.artifact_dir, exist_ok=True)
        os.makedirs(self.meta_dir, exist_ok=True)
        
        self.seq_len = self.config['data_pipeline']['feature_engineering']['sequence_length']
        self.n_splits = self.config['data_pipeline']['preprocessing']['cross_validation_folds']
        
        # State tracking
        self.feature_names = []
        self.oof_predictions = {} # Stores out-of-fold matrices for the meta-learner

    def _load_and_isolate_data(self) -> Tuple[np.ndarray, np.ndarray]:
        """
        Loads the pre-processed matrix. Dynamically excludes non-feature columns
        to support the highly advanced InstitutionalFeatureFactory without crashing.
        """
        logger.info(f"Mounting engineered data matrix from: {self.data_path}")
        
        if not os.path.exists(self.data_path):
            logger.critical(f"Data not found! Ensure feature_factory.py has run successfully.")
            sys.exit(1)
            
        df = pd.read_csv(self.data_path).sort_values(by='issue_id').reset_index(drop=True)
        initial_len = len(df)
        
        # Drop rows where massive rolling windows caused NaNs
        df = df.dropna().reset_index(drop=True)
        logger.info(f"Data Loaded. Dropped {initial_len - len(df)} NaN cascade rows. Available rows: {len(df)}")
        
        # DYNAMIC FEATURE DETECTION
        # We drop known targets and identifiers. Everything else is a feature.
        exclude_cols = ['issue_id', 'result_number', 'result_color', 'result_small_big', 'Size_Target']
        
        self.feature_names = [col for col in df.columns if col not in exclude_cols]
        logger.info(f"Dynamically detected {len(self.feature_names)} quantitative features.")
        
        # Isolate Tensors
        X = df[self.feature_names].values
        y = df['Size_Target'].values.astype(int)
        
        return X, y

    # ==========================================================================
    # XGBOOST IMPLEMENTATION
    # ==========================================================================
    def train_xgboost(self, X: np.ndarray, y: np.ndarray) -> np.ndarray:
        logger.info("-" * 70)
        logger.info("🚀 ENGINING XGBOOST ARCHITECTURE (Gradient Boosted Trees)")
        
        # Extract Hyperparameters safely (fallback if missing)
        xgb_cfg = self.config['models'].get('xgboost', {})
        n_estimators = xgb_cfg.get('n_estimators', 1000)
        learning_rate = xgb_cfg.get('learning_rate', 0.05)
        max_depth = xgb_cfg.get('max_depth', 6)
        
        cv = PurgedTimeSeriesSplit(n_splits=self.n_splits, purge_window=self.seq_len)
        oof_preds = np.zeros(len(X))
        
        for fold, (train_idx, val_idx) in enumerate(cv.split(X)):
            X_train, y_train = X[train_idx], y[train_idx]
            X_val, y_val = X[val_idx], y[val_idx]
            
            model = xgb.XGBClassifier(
                n_estimators=n_estimators,
                learning_rate=learning_rate,
                max_depth=max_depth,
                subsample=0.8,
                colsample_bytree=0.8,
                tree_method='hist', # Extremely fast for CPU
                eval_metric='auc',
                early_stopping_rounds=50,
                random_state=42 + fold,
                n_jobs=-1
            )
            
            model.fit(
                X_train, y_train,
                eval_set=[(X_val, y_val)],
                verbose=False
            )
            
            # Predict Probabilities
            preds = model.predict_proba(X_val)[:, 1]
            oof_preds[val_idx] = preds
            
            auc = roc_auc_score(y_val, preds)
            logger.info(f"XGBoost Fold {fold+1}/{self.n_splits} | Validation AUC: {auc:.4f}")
            
        # OOF Evaluation
        valid_indices = np.where(oof_preds > 0)[0] # Ignore purged/unpredicted rows
        metrics = TabularMetricsEvaluator.evaluate(y[valid_indices], oof_preds[valid_indices])
        TabularMetricsEvaluator.print_report("XGBoost", metrics)
        
        # Final Retrain on 100% Data for Production Inference
        logger.info("Training Production XGBoost Master Artifact on 100% data...")
        master_model = xgb.XGBClassifier(
            n_estimators=int(n_estimators * 0.8), # Prevent overfitting on final run
            learning_rate=learning_rate,
            max_depth=max_depth,
            tree_method='hist',
            random_state=42,
            n_jobs=-1
        )
        master_model.fit(X, y)
        
        # Serialization
        model_path = os.path.join(self.artifact_dir, "xgboost_master.json")
        master_model.save_model(model_path)
        logger.info(f"Artifact Saved: {model_path}")
        
        # Save Feature Importance Dictionary
        importance_dict = dict(zip(self.feature_names, master_model.feature_importances_))
        sorted_importance = {k: float(v) for k, v in sorted(importance_dict.items(), key=lambda item: item[1], reverse=True)}
        with open(os.path.join(self.artifact_dir, "xgboost_feature_importance.json"), 'w') as f:
            json.dump(sorted_importance, f, indent=4)
            
        return oof_preds

    # ==========================================================================
    # LIGHTGBM IMPLEMENTATION
    # ==========================================================================
    def train_lightgbm(self, X: np.ndarray, y: np.ndarray) -> np.ndarray:
        logger.info("-" * 70)
        logger.info("🚀 ENGINING LIGHTGBM ARCHITECTURE (Leaf-Wise Trees)")
        
        cv = PurgedTimeSeriesSplit(n_splits=self.n_splits, purge_window=self.seq_len)
        oof_preds = np.zeros(len(X))
        
        for fold, (train_idx, val_idx) in enumerate(cv.split(X)):
            X_train, y_train = X[train_idx], y[train_idx]
            X_val, y_val = X[val_idx], y[val_idx]
            
            model = lgb.LGBMClassifier(
                n_estimators=1000,
                learning_rate=0.03,
                num_leaves=31,
                max_depth=7,
                subsample=0.8,
                colsample_bytree=0.8,
                random_state=42 + fold,
                n_jobs=-1,
                importance_type='gain'
            )
            
            # LGBM implementation
            callbacks = [lgb.early_stopping(stopping_rounds=50, verbose=False)]
            
            model.fit(
                X_train, y_train,
                eval_set=[(X_val, y_val)],
                callbacks=callbacks
            )
            
            preds = model.predict_proba(X_val)[:, 1]
            oof_preds[val_idx] = preds
            
            auc = roc_auc_score(y_val, preds)
            logger.info(f"LightGBM Fold {fold+1}/{self.n_splits} | Validation AUC: {auc:.4f}")
            
        valid_indices = np.where(oof_preds > 0)[0]
        metrics = TabularMetricsEvaluator.evaluate(y[valid_indices], oof_preds[valid_indices])
        TabularMetricsEvaluator.print_report("LightGBM", metrics)
        
        logger.info("Training Production LightGBM Master Artifact on 100% data...")
        master_model = lgb.LGBMClassifier(
            n_estimators=800, learning_rate=0.03, num_leaves=31, random_state=42, n_jobs=-1
        )
        master_model.fit(X, y)
        
        model_path = os.path.join(self.artifact_dir, "lightgbm_master.txt")
        master_model.booster_.save_model(model_path)
        logger.info(f"Artifact Saved: {model_path}")
        
        return oof_preds

    # ==========================================================================
    # CATBOOST IMPLEMENTATION
    # ==========================================================================
    def train_catboost(self, X: np.ndarray, y: np.ndarray) -> np.ndarray:
        logger.info("-" * 70)
        if not CATBOOST_AVAILABLE:
            logger.warning("CatBoost not installed. Skipping this ensemble layer.")
            return np.zeros(len(X))
            
        logger.info("🚀 ENGINING CATBOOST ARCHITECTURE (Symmetric Trees)")
        
        cv = PurgedTimeSeriesSplit(n_splits=self.n_splits, purge_window=self.seq_len)
        oof_preds = np.zeros(len(X))
        
        for fold, (train_idx, val_idx) in enumerate(cv.split(X)):
            X_train, y_train = X[train_idx], y[train_idx]
            X_val, y_val = X[val_idx], y[val_idx]
            
            model = cb.CatBoostClassifier(
                iterations=1000,
                learning_rate=0.05,
                depth=6,
                eval_metric='AUC',
                random_seed=42 + fold,
                early_stopping_rounds=50,
                verbose=False,
                thread_count=-1
            )
            
            model.fit(X_train, y_train, eval_set=(X_val, y_val))
            
            preds = model.predict_proba(X_val)[:, 1]
            oof_preds[val_idx] = preds
            
            auc = roc_auc_score(y_val, preds)
            logger.info(f"CatBoost Fold {fold+1}/{self.n_splits} | Validation AUC: {auc:.4f}")
            
        valid_indices = np.where(oof_preds > 0)[0]
        if len(valid_indices) > 0:
            metrics = TabularMetricsEvaluator.evaluate(y[valid_indices], oof_preds[valid_indices])
            TabularMetricsEvaluator.print_report("CatBoost", metrics)
        
        logger.info("Training Production CatBoost Master Artifact on 100% data...")
        master_model = cb.CatBoostClassifier(
            iterations=800, learning_rate=0.05, depth=6, random_seed=42, verbose=False, thread_count=-1
        )
        master_model.fit(X, y)
        
        model_path = os.path.join(self.artifact_dir, "catboost_master.cbm")
        master_model.save_model(model_path)
        logger.info(f"Artifact Saved: {model_path}")
        
        return oof_preds

    # ==========================================================================
    # ORCHESTRATION & META-MATRIX COMPILATION
    # ==========================================================================
    def execute(self):
        """Drives the end-to-end training, evaluating, and matrix generation sequence."""
        
        # 1. Load Data
        X, y = self._load_and_isolate_data()
        
        if len(X) < 1000:
            logger.critical("Dataset is too small for institutional ensemble training. Aborting.")
            sys.exit(1)
            
        # 2. Train Models and gather OOF predictions
        oof_xgb = self.train_xgboost(X, y)
        oof_lgb = self.train_lightgbm(X, y)
        oof_cat = self.train_catboost(X, y)
        
        # 3. Assemble the Level-1 OOF Matrix
        logger.info("="*70)
        logger.info("COMPILING LEVEL-1 META-MATRIX FOR DEEP AGGREGATOR")
        
        # We only pass active models to the meta-matrix
        valid_matrices = []
        if np.any(oof_xgb): valid_matrices.append(oof_xgb)
        if np.any(oof_lgb): valid_matrices.append(oof_lgb)
        if np.any(oof_cat): valid_matrices.append(oof_cat)
        
        # Shape: (Samples, Num_Tabular_Models)
        meta_matrix = np.column_stack(valid_matrices)
        
        # Note: We must slice out the "purged" zeroes from the beginning of the OOF arrays
        # so the Meta-Learner trains purely on valid out-of-fold data.
        # Find the first index where all valid matrices have non-zero predictions
        valid_mask = np.all(meta_matrix > 0, axis=1)
        clean_meta_matrix = meta_matrix[valid_mask]
        clean_y_true = y[valid_mask]
        
        # 4. Save Matrix Artifacts
        meta_features_path = os.path.join(self.meta_dir, "tabular_oof_features.npy")
        meta_targets_path = os.path.join(self.meta_dir, "tabular_oof_targets.npy")
        
        np.save(meta_features_path, clean_meta_matrix)
        np.save(meta_targets_path, clean_y_true)
        
        logger.info(f"Level-1 Matrix Generated. Shape: {clean_meta_matrix.shape}")
        logger.info(f"Matrix serialized to: {self.meta_dir}")
        logger.info("="*70)
        logger.info("TABULAR ENSEMBLE TRAINING PHASE COMPLETE.")
        logger.info("="*70)


if __name__ == "__main__":
    engine = TabularEngine()
    engine.execute()